name: smart_farming
description: "smart farming aplikasi untuk monitoring dan kontrol pertanian secara otomatis menggunakan IoT"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  flutter_bloc: ^9.1.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  http: ^1.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# ⬇⬇⬇ INI HARUS DI LUAR flutter:
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg


# halolahdjakdnkamda